<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcommerceCandyHill.Application\EcommerceCandyHill.Application.csproj" />
    <ProjectReference Include="..\EcommerceCandyHill.Domain\EcommerceCandyHill.Domain.csproj" />
  </ItemGroup>

</Project>
