services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "SuaSenha123!"
      ACCEPT_EULA: "Y"
      MSSQL_ENCRYPT: "false"
    ports:
      - "1433:1433"
    volumes:
      - candyhillweb_sql_data:/var/opt/mssql   

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-api
    depends_on:
      - sqlserver
    ports:
      - "8080:80"
    environment:
      ConnectionStrings__CandyHillConnection: "Server=sqlserver;Database=CandyHill;User Id=sa;Password=SuaSenha123!;Encrypt=False;TrustServerCertificate=True;"

volumes:
  candyhillweb_sql_data:
    external: true

