<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="11.11.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EcommerceCandyHill.Application\EcommerceCandyHill.Application.csproj" />
		<ProjectReference Include="..\EcommerceCandyHill.Infra.Data\EcommerceCandyHill.Infra.Data.csproj" />
	</ItemGroup>

</Project>
